### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by andthink** [morrolinux/KindleCalendar#8]
I was following your instructions and...
`cd KindleCalendar && pip install -r requirements.txt && cd ..
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'`

Thanks for the interesting project!

**Comment by morrolinux** [comment]
Thanks for pointing that out, it should be fixed in #3 
Try with `git pull` inside the KindleCalendar folder and it should download the `requirements.txt`
